// Regenerates src/protocol/demo/demoDefinitionCompressed.data.ts — the xz-compressed,
// base64-encoded vial.json that MockHidTransport (src/protocol/demo/mockHidTransport.ts)
// serves for CMD_VIAL_GET_SIZE/CMD_VIAL_GET_DEFINITION when the user enters 功能预览
// (feature preview). Compressing it here (not at runtime) means MockHidTransport can hand
// the exact same xz bytes a real board would, exercising Keyboard.reload()'s real
// decompress-then-JSON.parse path — there's no in-browser xz *encoder* dependency (only
// xz-decompress, which only decodes), so this has to happen at generation time instead.
//
// Run after editing demoDefinition.ts:  node scripts/genDemoDefinition.mjs
// (Requires the `xz` CLI on PATH — matches what a real vial-qmk build's own tooling uses.)

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { DEMO_DEFINITION } from "../src/protocol/demo/demoDefinition.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(root, "src/protocol/demo/demoDefinitionCompressed.data.ts");

const json = JSON.stringify(DEMO_DEFINITION);
const compressed = execFileSync("xz", ["-9e", "-c", "-T", "1"], { input: json, maxBuffer: 1024 * 1024 });
const base64 = compressed.toString("base64");

writeFileSync(
  OUT,
  `// Generated by scripts/genDemoDefinition.mjs — do not edit by hand.
// Regenerate after changing demoDefinition.ts:  node scripts/genDemoDefinition.mjs

/** xz-compressed, base64-encoded JSON.stringify(DEMO_DEFINITION) from demoDefinition.ts. */
export const DEMO_DEFINITION_XZ_BASE64 = ${JSON.stringify(base64)};
`,
);

console.log(`wrote ${OUT} (${json.length} bytes -> ${compressed.length} compressed, ${base64.length} base64)`);
