// Regenerates src/mdiIcons.data.ts — the OFFLINE subset of Material Design Icons
// the app renders, so <Icon icon="mdi:…" /> resolves synchronously with no runtime
// hit to the Iconify API (no network, no bundling the full 3 MB mdi set).
//
// It scans src/ for every `mdi:<name>` string literal (both the UI-chrome icons
// and the keycap glyphs mapped in keycapIcons.ts), resolves each against
// @iconify-json/mdi — following aliases to their concrete parent — and writes the
// minimal { icons, aliases } collection back out.
//
// Run after adding/removing any mdi icon:  node scripts/genIcons.mjs
// (@iconify-json/mdi is a devDependency; this script never ships to the browser.)

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "src");
const MDI = join(root, "node_modules/@iconify-json/mdi/icons.json");
const OUT = join(root, "src/lib/mdiIcons.data.ts");

// --- 1. collect every mdi:<name> referenced in the source tree ------------------
function walk(dir) {
  const out = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const p = join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(p));
    else if (/\.(ts|tsx)$/.test(e.name) && !p.endsWith("mdiIcons.data.ts")) out.push(p);
  }
  return out;
}

const wanted = new Set();
for (const file of walk(SRC)) {
  const text = readFileSync(file, "utf8");
  for (const m of text.matchAll(/mdi:([a-z0-9-]+)/g)) wanted.add(m[1]);
}

// --- 2. resolve against the full mdi set, chasing aliases to real icons ---------
const mdi = JSON.parse(readFileSync(MDI, "utf8"));
const icons = {};
const aliases = {};

function resolve(name, seen = new Set()) {
  if (seen.has(name)) throw new Error(`alias cycle at mdi:${name}`);
  seen.add(name);
  if (mdi.icons[name]) {
    icons[name] = mdi.icons[name];
  } else if (mdi.aliases?.[name]) {
    aliases[name] = mdi.aliases[name];
    resolve(mdi.aliases[name].parent, seen); // ensure the parent icon is included
  } else {
    throw new Error(`mdi:${name} not found in @iconify-json/mdi`);
  }
}

for (const name of wanted) resolve(name);

// --- 3. emit the collection, keys sorted for a stable diff ----------------------
const sort = (o) => Object.fromEntries(Object.keys(o).sort().map((k) => [k, o[k]]));
const collection = { prefix: "mdi", width: mdi.width ?? 24, height: mdi.height ?? 24, icons: sort(icons) };
if (Object.keys(aliases).length) collection.aliases = sort(aliases);

const banner = `// AUTO-GENERATED by scripts/genIcons.mjs — do not edit by hand.
// Offline subset of @iconify-json/mdi holding only the ${Object.keys(icons).length} glyphs the app
// actually renders (keycap symbols + UI-chrome icons). Registered once at boot in
// mdiIcons.ts so every <Icon icon="mdi:…" /> resolves offline — no runtime Iconify
// API request, no bundling the full 3 MB set.
// Regenerate after changing any mdi icon:  node scripts/genIcons.mjs
import type { IconifyJSON } from "@iconify/react";

export const MDI_ICONS: IconifyJSON = `;

writeFileSync(OUT, `${banner}${JSON.stringify(collection)};\n`);
console.log(`wrote ${Object.keys(icons).length} icons + ${Object.keys(aliases).length} aliases → ${OUT}`);
